[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 7

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false
